name: Test CUDA-Rust Build

on: [workflow_dispatch]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up CUDA
        uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build CUDA and Rust
        env:
          NVCC_PREPEND_FLAGS: "-ccbin=gcc -std=c++17"
        run: |
          cd open-division/prize1-msm/prize1a-msm-gpu/matter-labs
          cargo build